version: '3.4'

services:
  linkapi.api:
    image: ${DOCKER_REGISTRY-}linkapi
    depends_on:
        - linkapi.database
    container_name: linkapi.api
    build:
      context: .
      dockerfile: linkApi/Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    environment:
       DB_CONNECTION_STRING: "Host=linkapi.database;Port=5432;Database=link_shortener;Username=postgres;Password=12345678"
       ASPNETCORE_ENVIRONMENT: "Development"
       ASPNETCORE_HTTP_PORTS: "5010"
       ASPNETCORE_HTTPS_PORTS: "5011"
       ASPNETCORE_Kestrel__Certificates__Default__Password: "1234"
       ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/linkapi.pfx"
    volumes:
       - ~/.aspnet/https:/https:ro

  linkapi.database:
    image: postgres:latest
    container_name: linkapi.postgres.database
    environment:
        - POSTGRES_DB=link_shortener
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345678
    volumes:
        - ./db_volume:/var/lib/postgres/data
        - ./DataContextPostgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
    restart: always

volumes:
   db_volume:   
    
 
